### PR TITLE
Updating README to be cleaner and more organized for the readers

### PR DESCRIPTION
**Pull request by Schachte**
@Jimnotgym Just some quick readme updates to make initial appearance more welcoming to readers: 

---------

##### Demo Photo of Markdown Changes

screen shot 2018-05-05 at 1 08 34 pm

### CODE REVIEW

**Comment by Jimnotgym** [comment]
I really like the changes. As you can see I don't have a flair for presentation like you. 

Do you think we are OK using the Hacker News logo like that? I wonder how that ages too, I mean at the moment most of the sources are from HN, but I can imagine a broader range of sources being added over time?

**Comment by Schachte** [comment]
Yah we can iterate on it.

**Comment by Jimnotgym** [comment]
Thanks for the contribution. I have merged your PR. It is really nice to have the first contributor raise a PR!

**Comment by Schachte** [comment]
@Jimnotgym Sure thing. Think you made a typo in your most recent push to master in the TOC. Be sure to keep the formatting consistent for the links to work correctly.

**Pull request merged**
